### ISSUE TITLE
install.py fix

### ISSUE THREAD

**Issue by smhooten** [anstmichaels/emopt#10]
I noticed that the current install.py script for emopt is broken. There are two issues:

1. PETSc recently changed their remote repository. It's now at
https://gitlab.com/petsc/petsc.git

2. PETSc and SLEPc updated recently, but the install script still points to the old version of SLEPc. I fixed this by specifying,
SLEPC_VERSION = "3.12.0"

Tested on Ubuntu 18.04 and CentOS 7

**Comment by totyped** [comment]
Hi !
I also noticed those two errors but I did not get it to work. Here is my complete issue: https://github.com/anstmichaels/emopt/issues/12
Would you mind to tell me if you did anything different from my changes to the install.py file ?

**Comment by anstmichaels** [comment]
Thanks for the heads up. I have fixed the PETSc download issues and pushed the new install.py.  The install.py should work now (and in the future as well--I have fixed the PETSc version number so it will match SLEPc).

@totyped Let's continue debugging your issue in the issue you posted.

**Comment by kaipengliuHIT** [comment]
when I run the install.py, I will get:
..............
link.mklink boost/numeric/interval.hpp
mklink-or-dir boost/numeric/odeint
mklink-or-dir boost/numeric/conversion
...updated 590 targets...
Cleaning up boost directories
Downloading PETSc...
HTTPSConnectionPool(host='ftp.mcs.anl.gov', port=443): Max retries exceeded with url: /pub/petsc/release-snapshots/petsc-3.12.1.tar.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f150b2b89d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
..............
Maybe I couldn't download the PETSc
