### ISSUE TITLE
About the application of the model

### ISSUE THREAD

**Issue by jiehuang008** [anstmichaels/emopt#2]
Hi, will you open you code about Ref. [1] ?

1. A. Michaels and E. Yablonovitch, “Gradient-Based Inverse Electromagnetic Design Using Continuously-Smoothed Boundaries,” Arxiv (2017).

Besides, can your model handel the problem which have multiple irregular boundaries (like the design result of Ref. [2]) ?

2. Piggott A Y, Lu J, Lagoudakis K G, et al. Inverse design and demonstration of a compact and broadband on-chip wavelength demultiplexer [J]. Nature Photonics, 2015, 9(6).

**Comment by anstmichaels** [comment]
Hi,

This code is an updated and "improved" version of the code used in writing ref [1]. I do not plan on releasing the original code as it is not nearly as user friendly nor well documented which would result more headache than it is worth. If you are interested in the application considered in [1], I may eventually port it over to this new code base.

The current code focuses on shape optimization. It can handle as many boundaries as you initially prescribe in the code. Ref [2] employs something akin to homogenization methods which allow permittivity to vary continuously between two values (this is different than explicitly manipulating boundaries). The resulting gray-scale distribution is eventually filtered in some manner in order to produce a binary material distribution. Technically, the code can handle such parameterizations already, however it will need some modification to do so more efficiently.

I have written the library in a way to make it easy to support new forms of shape or topology optimization. I do plan on eventually adding similar functionality, however not in the short term. If you need it for your own project, it would not be too hard to implement.

**Comment by jiehuang008** [comment]
Hi Michaels

Thank you for your reply. I don't know the address of your personal email, So I sent an email to the email
of emopt@noreply.github.com.

**Comment by anstmichaels** [comment]
I am not sure that email is functional?

**Comment by jiehuang008** [comment]
My email is jhuang_nudt@163.com, can you send me an email with your personal email address?

**Comment by jiehuang008** [comment]
Sorry, I might have done something wrong...

I think you can close this Issue now.
